services:
  # We laten Caddy even uitgeschakeld of ongewijzigd
  
  youtube-app:
    build: .
    restart: always
    ports:
      - "5002:8501" # We mappen de interne poort naar 5002 naar buiten

  merger-app:
    build:
      context: .
      dockerfile: Dockerfile.merger
    ports:
      - "5001:5001"
    restart: always