services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  youtube-app:
    build: .
    restart: always
    # Geen externe poorten, Caddy regelt de HTTPS-laag

  merger-app:
    build:
      context: .
      dockerfile: Dockerfile.merger
    ports:
      - "5001:5001" # Dit zet de deur naar de merger weer open op poort 5001
    restart: always

volumes:
  caddy_data:
  caddy_config: