services:
  youtube-app:
    build: .
    restart: always
    ports:
      - "5002:5000" # We sturen poort 5002 naar de interne Flask poort 5000
    env_file: .env # Zorg dat je .env met de nieuwe key ook hier gekoppeld is